//
// Created by chaku on 14/06/25.
//

#ifndef THE_RAYTRACER_CHALLENGE_SIMULATION_HPP
#define THE_RAYTRACER_CHALLENGE_SIMULATION_HPP

void simulate_projectile();

#endif //THE_RAYTRACER_CHALLENGE_SIMULATION_HPP
